### ISSUE TITLE
文章内代码块高亮样式丢失 / 复制按钮丢失 / 显示异常

### ISSUE THREAD

**Issue by kindyear** [MoXiaoXi233/PureSuck-theme#15]
# 设备信息
系统版本：Windows 11
浏览器：Chrome 130.0.6723.70
网址：https://www.kindyear.cn/
主题版本：1.2.3
PHP版本：8.3
# 复现过程
点击包含代码块的文章时会出现代码块高亮丢失，字符会被灰色背景包裹
以及一键复制按钮丢失，图示为效果以及F12控制台错误提示
![image](https://github.com/user-attachments/assets/e5cba3bb-4a8c-401d-8117-f319610d26e5)

# 其他补充
对不起我又来提issue了（之前好像遇到过当时好像没太注意，今天又遇见了就报告一下 TT

**Comment by MoXiaoXi233** [comment]
我尝试在你网站转了半天没能触发这个bug（）

**Comment by MoXiaoXi233** [comment]
我猜可能是TOC的JS出错导致堵塞了，不过没能复现，我会留意观察的，谢谢反馈

**Comment by kindyear** [comment]
目前的测试情况是这样的：
首次加载时样式丢失的：
![image](https://github.com/user-attachments/assets/5b3e2012-2bdf-478c-b06c-36dac4b0418e)
但是shi使用F5刷新就正常了
![image](https://github.com/user-attachments/assets/1c8d3b85-c992-4332-a1b7-c8fda0c68d0f)
但是令人困惑的是如果我点击页面的标题重新加载这个文章又会出现图1的情况

**Comment by MoXiaoXi233** [comment]
不知道为什么始终没能复现 T _ T

**Comment by kindyear** [comment]
如果你方便了话你可以试着远程我这边远程排查一下（我对php也不是很熟所以不太清楚他的工作流程

**Comment by MoXiaoXi233** [comment]
要不加个Q看看？我其实经验也不太丰富的说😭

**Comment by kindyear** [comment]
QQ: 2469732284
验证信息答案：Spark
