### ISSUE TITLE
主题升级到1.2.3后不兼容Dplayer插件

### ISSUE THREAD

**Issue by yanhuanzhi** [MoXiaoXi233/PureSuck-theme#16]

**Comment by yanhuanzhi** [comment]
系统版本：Windows 11
浏览器：Chrome 130.0.6723.70
网址：https://blog.kuetr.cn/archives/111/
主题版本：1.2.3
PHP版本：8.3

主题升级到1.2.3后，Dplayer的短代码不再解析了，直接将短代码显示出来。在上一个版本中正常

**Comment by yanhuanzhi** [comment]
![image](https://github.com/user-attachments/assets/cbb6226a-61ce-4196-9e28-c0267766ae60)

**Comment by MoXiaoXi233** [comment]
重新应用/安装一下主图吧

**Comment by MoXiaoXi233** [comment]
不过DPlayer的短代码也不是我负责的诶，回去看看原因

**Comment by yanhuanzhi** [comment]
好的，我试试

**Comment by MoXiaoXi233** [comment]
好的，确实是我这边的问题！没有考虑到其他插件的短代码解析
[修复外部插件短代码错误，加入Pjax回调函数设置](https://github.com/MoXiaoXi233/PureSuck-theme/commit/7c56ed9d67057c42369bb9a9b791081b21e766f5)
你可以先手动替换这两个文件，修复了这个问题并且在后台加入了pjax回调函数的接口

**Comment by yanhuanzhi** [comment]
修复啦~~ (* ￣3)
