### ISSUE TITLE
最新RC2版本评论问题仍未解决

### ISSUE THREAD

**Issue by LumingStudio** [MoXiaoXi233/PureSuck-theme#17]
已按照RC2版本的附加说明替换了comments.php文件，但是评论依然会出现undefined的情况，望修改，辛苦了

**Comment by MoXiaoXi233** [comment]
可以提供一个测试地址嘛，因为我不太确定复现方式了，很抱歉：（

**Comment by MoXiaoXi233** [comment]
> 还有就是评论区部分头像（如博主的头像）会显示异常，不知道是什么原因，挂梯子也是这样的情况（ ![image](https://private-user-images.githubusercontent.com/178443557/384411457-865eca02-db04-4f51-94d0-f1f407739b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc3MjIsIm5iZiI6MTczMTA3NzQyMiwicGF0aCI6Ii8xNzg0NDM1NTcvMzg0NDExNDU3LTg2NWVjYTAyLWRiMDQtNGY1MS05NGQwLWYxZjQwNzczOWI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDUwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWVkZTg0MDhiNWQyMGI2ZjRlZTZkYWQ2MDExNGZlYjcwY2E3M2Y2MTY2MzdlZTdiMmRmM2EzNmQzYWFmYjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dveuPTt8iWOORsgymuzljG6rdlcEhumed52BOsWes34) （辛苦了）

评论区的头像走的是Gavatar的国内镜像源，试试看是不是没设置头像什么的（应该是根据邮箱地址）？

**Comment by LumingStudio** [comment]
e，不能复现，估计是我这边的问题（
头像问题我知道了，我以为用的是Cravatar所以没设置（（
这个对PHP版本有什么要求吗？亦或是说，您可以把您的comments.php通过邮箱发给我一份吗？
我的邮箱kangluming@chgskj.cn
再次真心表示感谢！

**Comment by ScDuckXu** [comment]
Android 12 Via浏览器 Chrome 139 无法复现。

**Comment by ScDuckXu** [comment]
issue提出方网站i.riseforever.cn/i.klm2558.cn在清除浏览器缓存后均正常评论。

**Comment by MoXiaoXi233** [comment]
已确保 bug 确实解决，或许是用户部署问题，不过暂时也得到了解决

**Comment by MoXiaoXi233** [comment]
2025的最后一版更新找到了其他可能导致这个问题的地方，也进行了修复，应该是彻底根治了：）
