### ISSUE TITLE
[Feature attemped]希望添加左侧边栏按纽自定义

### ISSUE THREAD

**Issue by ArkYuki** [MoXiaoXi233/PureSuck-theme#18]
主题默认是只为公开页面创建边栏小按纽，无法自由配置，对于需要添加外链的需求不太容易，希望添加支持。

**Comment by MoXiaoXi233** [comment]
建议自行修改header.php，按钮的自定义暂时还没有什么想法
只是一两个外链的话自行改代码也很简单+快捷的

**Comment by ArkYuki** [comment]
目前就是在自定义代码部分自行添加实现的。
