### ISSUE TITLE
markdown 多层有序列表问题

### ISSUE THREAD

**Issue by rbtre** [MoXiaoXi233/PureSuck-theme#4]
<img width="188" alt="Screenshot 2024-08-26 at 13 40 02" src="https://github.com/user-attachments/assets/ae6e76d1-26a4-4169-9b9d-b44d0f94f734">

应该分层分别计数。

比如这样：

1. something
    1. something
    2. something
2. something

而不是持续累加。

**Comment by MoXiaoXi233** [comment]
不好意思！没有考虑到，完全没做适配，我研究一下给他做出来，谢谢反馈！

**Comment by rbtre** [comment]
感谢。

**Comment by MoXiaoXi233** [comment]
Hello，如果我没有搞错的话应该是酱紫的？(ฅ´ω`ฅ)
![image](https://github.com/user-attachments/assets/4afd8e21-3306-4154-a134-c34cfe853036)
![image](https://github.com/user-attachments/assets/d4d2052c-8cf5-4f42-958a-95e7783a51a9)

**Comment by rbtre** [comment]
啊对对对，就是这样，谢谢。
