### ISSUE TITLE
封面设置

### ISSUE THREAD

**Issue by manman-dong** [MoXiaoXi233/PureSuck-theme#5]
这个主题的封面怎么设置的？我在控制台、主题编辑和文章编辑都没看见？

**Comment by MoXiaoXi233** [comment]
文章页面添加 img 字段，字段内容填写图片地址，这部分内容在文档里有的。后期会考虑优化一下这个问题

**Comment by manman-dong** [comment]
好的，感谢。

还有一个问题，文章显示普通列表好像有点问题，就像这样：


<img width="728" alt="Snipaste_2024-09-12_21-53-51" src="https://github.com/user-attachments/assets/9af89181-7adc-4b23-a898-c6fe0b5f7a20">
<img width="1239" alt="Snipaste_2024-09-12_21-53-33" src="https://github.com/user-attachments/assets/99f4313a-68fc-42b1-9a76-dc74a5ca500f">
<img width="668" alt="Snipaste_2024-09-12_21-53-26" src="https://github.com/user-attachments/assets/8bb6a18a-9e6d-4b68-b536-2529f06449b7">


在预览之中，不会显示列表样式

**Comment by MoXiaoXi233** [comment]
> 好的，感谢。
> 
> 还有一个问题，文章显示普通列表好像有点问题，就像这样：
> 
> <img alt="Snipaste_2024-09-12_21-53-51" width="728" src="https://private-user-images.githubusercontent.com/82451196/366906422-9af89181-7adc-4b23-a898-c6fe0b5f7a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTAyMjAsIm5iZiI6MTcyNjE0OTkyMCwicGF0aCI6Ii84MjQ1MTE5Ni8zNjY5MDY0MjItOWFmODkxODEtN2FkYy00YjIzLWE4OTgtYzZmZTBiNWY3YTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE0MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMzkxMTFjMGRlM2UzZGRkN2RjM2Y5Njk4OTQ1ZWQ0OWU2N2ZmZTNkZmQzZWQ5OWUzMjY2YWYzYTZjZTgwMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DxsTPwtehrYJKOEhj3pwc2Tsh6C3ZTUVoj2kK_MfYNw"> <img alt="Snipaste_2024-09-12_21-53-33" width="1239" src="https://private-user-images.githubusercontent.com/82451196/366906435-99f4313a-68fc-42b1-9a76-dc74a5ca500f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTAyMjAsIm5iZiI6MTcyNjE0OTkyMCwicGF0aCI6Ii84MjQ1MTE5Ni8zNjY5MDY0MzUtOTlmNDMxM2EtNjhmYy00MmIxLTlhNzYtZGM3NGE1Y2E1MDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE0MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NTQzN2E0MjgzZWE1NGRiN2QzNmM5YWI5OTk2YmJiOGJkMDU3NDg4MjdlOTExYzk3ZmViMDc2YjIzYTAyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DXVkw-hkmC1OMbXfednqfOJzd03zYxb9VUgkbL7J30E"> <img alt="Snipaste_2024-09-12_21-53-26" width="668" src="https://private-user-images.githubusercontent.com/82451196/366906439-8bb6a18a-9e6d-4b68-b536-2529f06449b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTAyMjAsIm5iZiI6MTcyNjE0OTkyMCwicGF0aCI6Ii84MjQ1MTE5Ni8zNjY5MDY0MzktOGJiNmExOGEtOWU2ZC00YjY4LWI1MzYtMjUyOWYwNjQ0OWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE0MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YzUxNjBhNGI2YmU2ZWQ5OTcyMzQ2MDE3OTBlMWQ5Mzg3YjIyODAzZWMwOWQ4OGVmNDRiMjFlYzFlNWQ4MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ganedf_G3gwMv0grtxwsuwKD2Y0MCP2_ifAr7t0gTK0">
> 在预览之中，不会显示列表样式

复现成功···应该是我没写样式，我看看怎么解决

**Comment by manman-dong** [comment]
好的，感谢💕

**Comment by MoXiaoXi233** [comment]
> 好的，感谢💕

不确定修的有没有问题：）你直接拿最新的PureSuck_Style.CSS覆盖你现有的试试

**Comment by manman-dong** [comment]
> > 好的，感谢💕
> 
> 不确定修的有没有问题：）你直接拿最新的PureSuck_Style.CSS覆盖你现有的试试

把PureSuck_Module.css换了可以了😘
