### ISSUE TITLE
搜索框/标签 错位

### ISSUE THREAD

**Issue by Annran233** [MoXiaoXi233/PureSuck-theme#6]
如图所示，搜索框、分类与标签显示于文章卡片下方。
使用Typecho 1.2.1，PureSuck版本1.1.7，PHP版本8.0。
故障如图。
![PC端](https://github.com/user-attachments/assets/7a241b20-88cc-4a17-8df1-e49338ce7eb2)
![平板端](https://github.com/user-attachments/assets/efb0c37f-6747-41f3-81ff-6675e8c6bec9)

**Comment by MoXiaoXi233** [comment]
你干了什么嘛（）我怎么记得你的网站前几天还挺正常的

**Comment by MoXiaoXi233** [comment]
不太确定原因是什么，你可以重新下载1.1.7的压缩包然后替换css看看能不能解决

**Comment by MoXiaoXi233** [comment]
好的我找到原因了，我看看具体能不能尝试避免（貌似是你在底栏留的超链接和这个地方发生了什么奇妙的化学反应）

**Comment by MoXiaoXi233** [comment]
这边注意到你没有通过正常的方法将底部的信息填进去？而是直接自己修改添加了对应的内容？按道理后台是有提供底部信息的位置的，要让信息在nav main-lastinfo标签内才不会出现这个问题：）

**Comment by Annran233** [comment]
出现了，犯大乌龙了，~~把网站底部信息直接填到Script标签里了~~。
十分抱歉啊啊啊啊啊！！！
