### ISSUE TITLE
无序列表

### ISSUE THREAD

**Issue by rbtre** [MoXiaoXi233/PureSuck-theme#7]
。。。上次说那个有序列表嵌套的问题来着。。。但是改了之后咋不支持无需列表了。。

* something.
* something.
* something.

像这样，但是丢这个主题里就变成有序列表了。。。还是把无序列表加回来吧（
谢谢！

**Comment by MoXiaoXi233** [comment]
[文章显示普通列表好像有点问题](https://github.com/MoXiaoXi233/PureSuck-theme/issues/5)你可以先看看这个，我这边还没完全处理好。。

**Comment by MoXiaoXi233** [comment]
试试新版本的css :)不过这次加的功能有点多，可以都看看
