### ISSUE TITLE
建议添加 Pjax跳转

### ISSUE THREAD

**Issue by God-2077** [MoXiaoXi233/PureSuck-theme#9]
建议添加 Pjax跳转，页面跳转会更加平滑，更好看。

**Comment by MoXiaoXi233** [comment]
其实我尝试过了······个人能力实在没能解决各种BUG😢希望有人能着手帮我完成适配吧，悲

**Comment by God-2077** [comment]
我看一下了，还有，你短代码是丢前端处理的呀

**Comment by God-2077** [comment]
添加了 Pjax，能正常跳转，正常评论，但有可能不通过 Pjax 直接跳转的。

https://github.com/God-2077/PureSuck-theme

**Comment by MoXiaoXi233** [comment]
> 我看一下了，还有，你短代码是丢前端处理的呀

还能在后端处理嘛··🫡

**Comment by MoXiaoXi233** [comment]
> 添加了 Pjax，能正常跳转，正常评论，但有可能不通过 Pjax 直接跳转的。
> 
> https://github.com/God-2077/PureSuck-theme

感谢，让我学习一下

**Comment by MoXiaoXi233** [comment]
> 添加了 Pjax，能正常跳转，正常评论，但有可能不通过 Pjax 直接跳转的。
> 
> https://github.com/God-2077/PureSuck-theme

还是有很多和我一样的 BUG，哈哈哈，不过项目本身也要慢慢磨一段时间，我先拉取过来慢慢修改了，谢谢你！

**Comment by MoXiaoXi233** [comment]
> 添加了 Pjax，能正常跳转，正常评论，但有可能不通过 Pjax 直接跳转的。
> 
> https://github.com/God-2077/PureSuck-theme

**根据你的帮助已经基本完成了Pjax的所有工作！**
不通过 Pjax 跳转的问题已经找到并解决了，相关的回调函数我也加入进去了。
此前我一直以为Pjax要指定更新容器和不更新的容器，还需要调整结构，没想到有这么简洁的实现，看来或许是因为我找到的教程都太过时了😘

**Comment by God-2077** [comment]
> > 添加了 Pjax，能正常跳转，正常评论，但有可能不通过 Pjax 直接跳转的。
> > https://github.com/God-2077/PureSuck-theme
> 
> 还是有很多和我一样的 BUG，哈哈哈，不过项目本身也要慢慢磨一段时间，我先拉取过来慢慢修改了，谢谢你！

最讨厌的 BUG 是它既没有报错也没有按预期运行，这让我上哪解决问题？

**Comment by God-2077** [comment]
> > 添加了 Pjax，能正常跳转，正常评论，但有可能不通过 Pjax 直接跳转的。
> > https://github.com/God-2077/PureSuck-theme
> 
> **根据你的帮助已经基本完成了Pjax的所有工作！** 不通过 Pjax 跳转的问题已经找到并解决了，相关的回调函数我也加入进去了。 此前我一直以为Pjax要指定更新容器和不更新的容器，还需要调整结构，没想到有这么简洁的实现，看来或许是因为我找到的教程都太过时了😘

我之前也在网上找过相关的 Pjax 教程，但它清一色都是 JQ + Pjax，而且教程复杂(看了几眼就晕了)，直到后来才在 github 看到个简洁的 Pjax 项目。

**Comment by MoXiaoXi233** [comment]
> > > 添加了 Pjax，能正常跳转，正常评论，但有可能不通过 Pjax 直接跳转的。
> > > https://github.com/God-2077/PureSuck-theme
> > 
> > 
> > **根据你的帮助已经基本完成了Pjax的所有工作！** 不通过 Pjax 跳转的问题已经找到并解决了，相关的回调函数我也加入进去了。 此前我一直以为Pjax要指定更新容器和不更新的容器，还需要调整结构，没想到有这么简洁的实现，看来或许是因为我找到的教程都太过时了😘
> 
> 我之前也在网上找过相关的 Pjax 教程，但它清一色都是 JQ + Pjax，而且教程复杂(看了几眼就晕了)，直到后来才在 github 看到个简洁的 Pjax 项目。

方便的话可以+个Q
现在这个pjax还是挺多问题的，细枝末节的地方
